### ISSUE TITLE
新建频道无法增加规则

### ISSUE THREAD

**Issue by SagittariusZhu** [SagittariusZhu/wxmblog#19]
增加规则时后台报错：

org.apache.ibatis.binding.BindingException: Mapper method 'com.apollo.amb.weixin.mapper.ChannelSubscribeMapper.getMaxID attempted t
o return null from a method with a primitive return type (int).
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:93) ~[mybatis-3.4.2.jar!/:3.4.2]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59) ~[mybatis-3.4.2.jar!/:3.4.2]
        at com.sun.proxy.$Proxy103.getMaxID(Unknown Source) ~[na:na]
        at com.apollo.amb.weixin.service.DataServiceImpl.storeSubscribeRule(DataServiceImpl.java:447) ~[classes!/:0.1.0]

**Comment by SagittariusZhu** [comment]
对空表执行max()操作时返回NULL，导致上述错误，修改sql为
select IFNULL(max(...),0)...
